### ISSUE TITLE
Reducing compiler warnings

### ISSUE THREAD

**Issue by d7919** [boutproject/BOUT-dev#322] opened 2016-10-18 13:18 UTC
As part of recent efforts to test the next branch I've started compiling with as many compiler warnings enabled as possible (`-Wall -Wextra -Wpedantic`). This generates `14365` lines of extra output (up to 5 lines per warning). Note this is with 

```
> g++ --version
g++ (SUSE Linux) 4.8.3 20140627 [gcc-4_8-branch revision 212064]
```

Extracting the unique warnings and counting (done using `make 2>ERRS ; grep "\[\-W" ERRS | awk -F"[" '{print $2}' | awk -F"]" '{print $1}' | sort | uniq -c | sort -nr | awk '{print "|\t" $1 "\t|" $2 "\t|"}'`) I find:

| Count | Warning |
| --- | --- |
| 3667 | unused parameter |
| 510 | reorder |
| 359 | pedantic |
| 205 | ignored qualifiers |
| 58 | missing field initializers |
| 29 | return type |
| 22 | unknown pragmas |
| 19 | unused variable |
| 12 | sign compare |
| 10 | unused but set variable |
| 6 | vla |
| 6 | deprecated declarations |
| 5 | unused value |
| 5 | switch |
| 3 | init self |
| 3 | format= |
| 1 | delete non virtual dtor |

In other words we're dominated by a few types of warning. Further I can note that some of these warnings are repeated in multiple places for the same line of source code (e.g. the `reorder` warning appears wherever we construct certain object instances so these 510 warnings can probably be fixed with just a few lines changed).

I would be keen to try to eliminate as many of these warnings as possible. One reason for this is that some of these warnings indicate code that can lead to undefined behaviour. I suspect I won't be able to fix everything simply but I may try to pick some of the low hanging fruit for now. I propose using this issue to keep track of efforts to remove/improve these warnings.

I expect a lot of the fixes will involve relatively minor changes (for example e185e38d148d6a440e00c12e0b04e49645273038 fixes the "delete non virtual dtor" warning which could potentially have led to undefined behaviour) but may touch lots of files.

**Comment by d7919** [comment] 2016-10-18 13:40
The `format=` warning results form three lines in `domain.cxx` of the form:

~~~
fprintf(stderr, "%x: (%d, %d) %d [%d, %d] [%d, %d]",
                this, nx, ny, s, bndry->getMin(s), bndry->getMax(s), b->getMin(s), b->getMax(s));
~~~

(the full warning is `warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 3 has type ‘Domain*’`).

My understanding is that when we want to print the pointer address we should use the `%p` format and actively cast the pointer as `(void*)`. This would change the above line to 

~~~
fprintf(stderr, "%p: (%d, %d) %d [%d, %d] [%d, %d]",
                (void*)this, nx, ny, s, bndry->getMin(s), bndry->getMax(s), b->getMin(s), b->getMax(s));
~~~

See [here](http://stackoverflow.com/a/9053835) for a discussion of this.

**Comment by d7919** [comment] 2016-10-18 13:52
format warning fixed in 0b90e0b87553b87a22e57fe54534f8326e4f1f2b

**Comment by d7919** [comment] 2016-10-18 13:52
`self init` warnings fixed in f280328217fb4335056e391ab2d26f0a92e4eb86

**Comment by dschwoerer** [comment] 2016-10-18 14:02
If I remember correctly `%p` is not C++, but rather C. It is supported by g++, and I think also by clang.

We could also explicitly cast to an usingned int - if you loose a part of the address of the object should be perfectly fine in most cases, it should still uniquely identify the object ...

**Comment by d7919** [comment] 2016-10-18 16:03
Thanks, I'm not that familiar with the different standards but looking in the [standard](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4296.pdf) (sections 22.4.2.1.2 and 22.4.2.2.2)  I can at least find reference to the `%p` format specifier. I'm not sure this is conclusive proof that this will always be ok (and I'm happy if there's a better/preferred alternative).

**Comment by bendudson** [comment] 2016-10-18 16:29
Useful to know about %p.  Perhaps worth pointing out that this domains.cxx
code is not used yet, and this code to print pointers was just for
development/debugging. Eventually the plan was to use the code to remove
the constraint that every processor has the same local index ranges.

**Comment by d7919** [comment] 2016-10-18 16:33
Yes, I thought I hadn't come across this bit of code before when profiling etc.! 

My thought is that if there are small, simple, fixes that remove warnings then it can be helpful to make the change even if it doesn't impact the typical operation just because it means we can more easily focus on the warnings that remain (even turning `-Wall` on by default for debug/check cases?).

**Comment by d7919** [comment] 2016-10-18 16:44
Just made four commits that remove the `reorder` warning. An example of why this could be an issue is [here](http://stackoverflow.com/a/1828048). Don't think this has been a problem for bout++

**Comment by d7919** [comment] 2016-10-18 17:08
The `ignored qualifier` warnings all arise from `include/bout/array.hxx`, lines 182 and 185. This is where we define 

~~~~
const_iterator begin() const
const_iterator end() const 
~~~~

and it's telling us the the `const` qualifier is being ignored. 

Firstly I should say I'm not expert in iterators vs. const_iterators etc. and I've not really gone through this in detail but I wonder if this could have an important consequence for compiler optimisation (or not). The compiler clearly knows that the returns are not `const` so it won't be able to take advantage of us not modifying this (assuming that we respect this `const` intent).

Would it be "safer/clearer" to not provide a const_iterator until/unless it is actually giving `const` returns? (again I may be missing something here in the purpose of the `const_iterator`).

**Comment by d7919** [comment] 2016-10-18 17:20
The `pedantic` warnings all arise from extra trailing `;` in various places across a number of files (I'd probably only want to fix this when all other development was quiet to prevent too many merge headaches).

The `missing field initializers` all arise from `index_derivs` where the lookup tables all terminate with a default entry which doesn't specify the long or short description. This is unlikely to cause any issues, but equally would probably be relatively easy to "fix" by ensuring all entries have a complete initialisation.

**Comment by d7919** [comment] 2016-10-18 17:45
Along with #318 this [branch](https://github.com/boutproject/BOUT-dev/tree/warning-fix-returnType) should fix all the return type warnings.

**Comment by d7919** [comment] 2016-10-18 17:54
The `pragma` warnings all derive from `#pragma omp parallel for` and `#pragma omp critical` statements in a few different files. Whilst these should usually be ignored if not compiled with `-fopenmp` (or equivalent) I think it's worthwhile to point out that on some systems (e.g. Archer) the default compiler defaults to activating `OpenMP` so I think it would be a good idea to look at encapsulating these pragmas in `#ifdef _OPENMP` type blocks or similar? I'm also not sure how reliable/well tested all these instances of `omp` are.

**Comment by dschwoerer** [comment] 2016-10-18 19:10
If you run `./configure` with the cray compiler, than it should add `-h noomp` to disable openmp. (just tested on master)

After a bit of SO, I think we could use:
```
#define STRINGIZE(A) #A
#ifdef _OPENMP
#define OMP_PRAGMA(f1) _Pragma(STRINGIZE(omp f1))
#else
#define OMP_PRAGMA(f1)
#endif
```
which can be used as
```
  OMP_PRAGMA(parallel)
  {
    printf("fu\n");
  }
```

**Comment by d7919** [comment] 2016-10-19 07:12
Ah ok, that's good to know. I've had issues with other codes in the past which weren't "cray aware".

That looks like it could be useful in providing a simple and consistent way of controlling `OpenMP` if it's robust and portable (which it looks like it should be).

**Comment by d7919** [comment] 2016-10-19 09:57
PR #325 provides fixes for several of the warnings given in the first post. The updated warnings count is now:

|Count | Warning|
|--------|------------|
|	3667	|-Wunused-parameter	|
|	359	|-Wpedantic	|
|	205	|-Wignored-qualifiers	|
|	58	|-Wmissing-field-initializers	|
|	22	|-Wunknown-pragmas	|
|	19	|-Wunused-variable	|
|	13	|-Wreturn-type	|
|	12	|-Wsign-compare	|
|	6	|-Wvla	|
|	6	|-Wunused-but-set-variable	|
|	6	|-Wdeprecated-declarations	|
|	5	|-Wunused-value	|
|	5	|-Wswitch	|

Note #318 removes the rest of the "return-type" warnings.

**Comment by ZedThree** [comment] 2016-10-20 16:10
With `clang` 3.5.0, latest `next`:

**Count** | **Warning**
---|---
3583 | unused-parameter
887  | overloaded-virtual
50   | ignored-qualifiers
18   | sign-compare
16   | return-type
9    | missing-field-initializers
6    | unused-variable
6    | deprecated-declarations
5    | vla-extension
4    | unused-private-field
4    | switch
1    | unused-comparison

Looks like it probably catches most of the same errors, but there's some new ones, I think.

**Comment by ZedThree** [comment] 2016-10-20 16:26
The same for `gnu 6.1.1`:

**Count** | **Warning**
---|---
3578 | unused-parameter
278  | pedantic
214  | ignored-qualifiers
164  | literal-suffix
58   | missing-field-initializers
22   | unknown-pragmas
18   | sign-compare
16   | return-type
6    | unused-variable
6    | deprecated-declarations
5    | vla
5    | unused-value
5    | unused-but-set-variable
5    | switch
3    | maybe-uninitialized

**Comment by ZedThree** [comment] 2016-10-21 10:32
I've been blindly applying the macro defined in [this SO question](http://stackoverflow.com/questions/7090998/portable-unused-parameter-macro-used-on-function-signature-for-c-and-c), and I've reduced the number of unused parameter warnings to about 900.
However, I think it will be necessary to go through and double-check each one individually, as there are definitely some instances where either the parameter can be removed entirely, or it should actually be used somewhere, e.g. [here][1] and [here][2].

[1]: https://github.com/boutproject/BOUT-dev/blob/next/src/field/initialprofiles.cxx#L135
[2]: https://github.com/boutproject/BOUT-dev/blob/next/src/field/field_data.cxx#L47

**Comment by ZedThree** [comment] 2016-10-26 16:42
`gnu 4.8.3` currently:

**Count** | **Warning**
---|---
241 | pedantic
212 | ignored-qualifiers
58  | missing-field-initializers
52  | unused-parameter
22  | unknown-pragmas
18  | sign-compare
6   | deprecated-declarations
5   | vla
5   | unused-variable
5   | unused-value
5   | unused-but-set-variable
4   | switch
3   | maybe-uninitialized

**Comment by ZedThree** [comment] 2016-10-27 16:58
#341 reduces this down to:

**Count** | **Warning**
---|---
52 | unused-parameter
6  | deprecated-declarations
5  | unused-variable
4  | unused-private-field

using `clang 3.5.0`

**Comment by ZedThree** [comment] 2016-10-28 10:01
`-Wpedantic` only gives `extra ';'` warnings, which are probably fine. Most of them are from macros field{2,3}d.cxx used to create functions/operators. There's no semicolon to remove from the macro definition, and removing the semicolon from the macro use makes my text editor get confused about indentation.

I vote we don't care about `-Wpedantic`, unless we fancy re-implementing the macros as templates or something.

**Comment by dschwoerer** [comment] 2016-10-28 15:00
I am not sure it is possible doing this using templates, as that would require having all this code in the header file, and being generated each time it is used - which I don't think is beneficial.

I have been thinking of auto-generate this code using a python script - this way it should be easy to generate the code for all possible combination of fields, etc. It would also allow to convince the compiler that he can use SIMD instruction.

I have done similar things to rewrite the derivatives for the AIOLOS-mesh ...

I guess a speed-up of 2 or 3 would be possible (for the multiplication, addition etc) this way, but I am not sure what your thoughts about auto-generated code are?

**Comment by ZedThree** [comment] 2016-10-28 16:44
I was thinking more like the macros would be replaced by a function, templated on the argument type (Field2D/Field3D/BoutReal), that takes an operator and applies it to the field. So instead of

    F3D_UPDATE_FIELD(+=, +, Field3D);    // operator+= Field3D
    F3D_UPDATE_FIELD(+=, +, Field2D);    // operator+= Field2D
    F3D_UPDATE_REAL(+=,+);    // operator+= BoutReal

we'd end up with something like:

    template<typename T>
    Field3D& Field3D::operator+=(const T &rhs) {
         return magic_function(Field3D::operator+, this, rhs);
    }

where `magic_function` is something like the body of `F3D_UPDATE_FIELD` currently, but explicitly taking the function to apply. For the `TRACE` message, we can use `typeid().name` (possibly with some demangling magic).

This code would be in the exact same place it is now.

I'm not overly keen on including auto-generated code, but if it's the best way to do it, then that's that!

**Comment by ZedThree** [comment] 2016-10-28 16:46
Last few commits to #341 now bring the number of warnings down to (`gnu 6.1.1`):

**Count** | **Warning**
---|---
110 | pedantic
52  | unused-parameter
22  | unknown-pragmas
6   | deprecated-declarations
2   | maybe-uninitialized

Most of these are "won't fix" for now, I think.

**Comment by d7919** [comment] 2016-12-06 18:03
@ZedThree have you been able to check that rc4 hasn't brought any of these back?

**Comment by ZedThree** [comment] 2016-12-09 17:23
Here's a summary of rc4 with gcc 4.8, 6.1 and clang 3.5 (I've dropped the `pedantic` warnings)

---
## gcc 4.8

**Count** | **Warning**
---|---
138 | unknown-pragmas
68  | unused-parameter
13  | deprecated-declarations
10  | unused-variable
6   | return-type
5   | maybe-uninitialized
2   | unused-but-set-variable
1   | vla

## gcc 6.1

**Count** | **Warning**
---|---
138 | unknown-pragmas
68  | unused-parameter
21  | deprecated-declarations
10  | unused-variable
6   | return-type
5   | maybe-uninitialized
2   | unused-but-set-variable

## clang 3.5

**Count** | **Warning**
---|---
68 | unused-parameter
16 | unused-private-field
13 | deprecated-declarations
10 | unused-variable
6  | return-type

---

Surprising that clang picks up the fewest warnings this time.

**Comment by ZedThree** [comment] 2016-12-12 17:45
#415 fixes a bunch of these. Now looks like:

## gcc 6.1.1 

with `-fopenmp` to silence `unknown-pragmas`

**Count** | **Warning**
---|---
68 | unused-parameter
16 | deprecated-declarations
5  | maybe-uninitialized
2  | unused-but-set-variable

## clang 3.5

**Count** | **Warning**
---|---
68 | unused-parameter
8  | deprecated-declarations

---

The multigrid stuff is responsible for the majority of the new warnings.

The deprecated declarations are all `Mesh::getXComm()` which doesn't have a suitable replacement yet. GNU also reports implementations of deprecated virtual functions, so it reports the definition of `Field2D::getData` etc. as additional warnings.

**Comment by dschwoerer** [comment] 2016-12-12 19:25
Why is it deprecated, if it is needed and there is no better alternative?
I think this function shouldn't be declared deprecated, unless it can be replaced, by a better/cleaner interface.

See also #405

**Comment by ZedThree** [comment] 2016-12-13 10:40
It's deprecated because it shouldn't be used in anything new. If you're writing something new, you should be using `Mesh::getXcomm(int jy)` instead, which is the better interface. The problem is that it's a little tricky to replace some of the existing uses of `getXcomm()`.

**Comment by d7919** [comment] 2017-02-02 09:18
Can this be closed now? Maybe we should update with the report from the next release when it's released and then close?

**Comment by ZedThree** [comment] 2017-08-09 16:49
With GCC 6.1.1, after removing the get/setData stuff from the various fields, the warnings look like this:

- with openmp enabled:

**Count** | **Warning**
---|---
67 | unused-parameter
5   | maybe-uninitialized
2   | unused-but-set-variable
1   | deprecated-declarations

- without openmp:

**Count** | **Warning**
---|---
138 | unknown-pragmas
67  | unused-parameter
5   | maybe-uninitialized
2   | unused-but-set-variable
1   | deprecated-declarations

This is in the v4.1-RC-tidy branch

**Comment by ZedThree** [comment] 2017-08-10 15:21
Clang:

**Count** | **Warning**
---|---
57 | unused-parameter
1  | unused-private-field

The unused private field is `Solver::enablerestart` -- can this be safely removed?

**Comment by d7919** [comment] 2017-08-10 15:24
`enablerestart` is referenced in one test (`tetst-integrate`) and in the manual under time integration. I think this should be removable.

**Comment by bendudson** [comment] 2017-08-10 16:11
I think it was intended for cases where a solver was needed e.g to integrate field lines, but should not read restart files. If it's never used then I guess it can be removed

**Comment by ZedThree** [comment] 2017-08-11 11:08
With the current state of v4.1-RC, we're now down to:

**Count** | **Warning**
---|---
5 | maybe-uninitialized
3 | unused-parameter
1 | deprecated-declarations

I think all of the maybe-uninitialised warnings are actually ok -- there's two from arkode/cvode for the vectors that get set from the strange macros. The other three are in the multigrid solver, but as far as I can tell, they will always be set to something. I'm not sure why the compiler thinks otherwise. All five are therefore "won't fix".

The three unused parameters are from the function in #644. These might actually be a bug.

The deprecated warning is from addToRestart -- I think this could be fixed? Or left in till 4.2?

Here's the complete list of warnings:
[gcc-6.txt](https://github.com/boutproject/BOUT-dev/files/1217655/gcc-6.txt)

With just `-Wall`, the unused-parameters vanish, so we only have 6 warnings. We could then maybe turn `-Wall` (or equivalent) on by default?

**Comment by ZedThree** [comment] 2017-08-11 16:26
I fixed the two from arkode/cvode by just initialising them to `nullptr`

**Comment by d7919** [comment] 2017-09-21 10:35
Is there anything to update with this now that 4.1 has been released?

**Comment by bendudson** [comment] 2017-10-11 06:20
After this heroic effort to squash warnings, I think this issue is done for now... Thanks everyone, particularly @ZedThree !

**Closed by bendudson** 2017-10-11 06:20 UTC
Labels: enhance request, possible bug
