### ISSUE TITLE
test-invpar timing out

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#2185] opened 2020-12-29 15:51 UTC
`test-invpar` keeps timing out in the debug CI build. Options:
* make a shorter version of the test, with fewer combinations of options, and mark the current one as `all_tests`
* increase the timeout for `test-invpar`
* increase the timeout for the debug CI build
* other suggestions?

**Comment by ZedThree** [comment] 2021-01-04 10:57
`test-drift-instability-staggered` is also timing out.

Actually, looks like everything has slowed down across the board for debug builds:

|                                 | #2164     | 7d4d427      |
|---------------------------------|-------------|--------------|
| test-code-style                 | ✓   0.071 s | ✓   0.225 s |
| test-command-args               | ✓  12.123 s | ✓  16.719 s |
| test-communications             | ✓  72.113 s | ✓  85.884 s |
| test-coordinates-initialization | ✓   0.768 s | ✓   1.183 s |
| test-cyclic                     | ✓  10.978 s | ✓  17.765 s |
| test-delp2                      | ✓  32.179 s | ✓  60.645 s |
| test-drift-instability-staggered| ✓ 148.480 s | 💤 300.006 s |
| test-fieldfactory               | ✓   3.581 s | ✓   5.856 s |
| test-griddata                   | ✓   0.877 s | ✓   1.601 s |
| test-griddata-yboundary-guards  | ✓  24.318 s | ✓  28.254 s |
| test-gyro                       | ✓   4.227 s | ✓   6.282 s |
| test-initial                    | ✓  18.776 s | ✓  28.354 s |
| test-interchange-instability    | ✓ 130.239 s | ✓ 188.292 s |
| test-interpolate                | ✓  12.111 s | ✓  21.008 s |
| test-interpolate-z              | ✓   3.555 s | ✓   4.084 s |
| test-invertable-operator        | ✓   1.815 s | ✓   2.328 s |
| test-invpar                     | ✓ 195.222 s | 💤 300.016 s |
| test-io                         | ✓  54.116 s | ✓  87.950 s |
| test-io_hdf5                    | ✓  34.380 s | ✓  52.547 s |
| test-laplace                    | ✓   5.453 s | ✓   8.991 s |
| test-laplace-petsc3d            | ✓  24.500 s | ✓  47.673 s |
| test-laplacexy-fv               | ✓  46.032 s | ✓  60.678 s |
| test-laplacexy-short            | ✓  84.505 s | ✓ 115.010 s |
| test-multigrid_laplace          | ✓  19.080 s | ✓  31.185 s |
| test-naulin-laplace             | ✓   7.858 s | ✓  10.936 s |
| test-options-netcdf             | ✓   0.796 s | ✓   1.695 s |
| test-region-iterator            | ✓   1.907 s | ✓   2.343 s |
| test-restart-io                 | ✓   4.948 s | ✓   7.873 s |
| test-restart-io_hdf5            | ✓   3.000 s | ✓   4.438 s |
| test-restarting                 | ✓   4.570 s | ✓   8.782 s |
| test-slepc-solver               | ✓   1.003 s | ✓   1.722 s |
| test-smooth                     | ✓   4.389 s | ✓   7.023 s |
| test-snb                        | ✓   0.659 s | ✓   1.262 s |
| test-solver                     | ✓ 104.793 s | ✓ 178.893 s |
| test-stopCheck                  | ✓   0.029 s | ✓   0.186 s |
| test-stopCheck-file             | ✓   5.671 s | ✓   8.598 s |
| test-subdir                     | ✓   1.216 s | ✓   2.025 s |
| test-twistshift                 | ✓   0.821 s | ✓   1.544 s |
| test-twistshift-staggered       | ✓   0.835 s | ✓   1.661 s |
| test-vec                        | ✓   2.146 s | ✓   3.176 s |
| test-yupdown                    | ✓   1.769 s | ✓   3.980 s |
| test-yupdown-weights            | ✓   0.929 s | ✓   2.019 s |

These are the PRs merged after #2164:

- #2140
- #2176
- #2144
- #2184
- #2064
- #1974
- #2030
- #2183
- #2187
- #2142
- #2190
- #2188
- #2193

It looks like #2184 is the first build that has the tests timing out, which is incredibly surprising given that's basically just touching documentation and removing IDL code!

It also looks like it's only the debug job that's slowed down.

I've dug through the Actions logs and can't see anything obvious, so I think I'm going to have to bisect this locally.

**Comment by ZedThree** [comment] 2021-01-04 16:49
Well, I bisected it on my machine and thought there was an obvious, major performance regression -- factor 10 slowdown for `test-invpar`. Turns out what I actually found was that #2087 adds a lot more individual tests to `test-invpar`!

I didn't see an obvious timing difference locally in any of the other tests, including `test-drift-instability-staggered`.

Given that the first time it failed was with the PR removing hypnotoad, I suspect it's likely a problem on the Github end, but I can't see what's changed.

Looking at the commit history here: https://github.com/boutproject/BOUT-dev/commits/next
it's a bit more obvious the test is actually bouncing (it's a little obscured after #2142 was merged, but the failing tests are actually in different builds, so it's still possible to see the timeouts bouncing).  It's pretty annoying, because random timeouts where something I thought we were done with after Travis!

I can't reproduce this locally, so there's really not much to go on. Bumping the timeout on GHA to 400s seems like the most pragmatic thing to do for now, although I'm not terribly happy about it. I'll do that in #2197 so that PR fixes both issues.

**Comment by bendudson** [comment] 2021-01-04 16:53
Thanks @ZedThree this is pretty strange.

**Comment by ZedThree** [comment] 2021-01-04 17:49
Clear demonstration that it's non-deterministic: https://github.com/boutproject/BOUT-dev/actions/runs/461472988

The difference between the top two builds is just an Actions variable, with the first (passing) option to be what's currently in next.

**Comment by johnomotani** [comment] 2021-01-05 22:52
I just looked at `test-invpar` again, and I think the number of combinations that it's testing now is excessive (my fault in #2087). I'd suggest the best thing is probably to keep the current version under all_tests, but for the regular test do most of the different coefficients just at CELL_CENTRE, and only test different locations for some 'most-typical' case (maybe the one with non-zero `bcoef` that inverts the parallel diffusion operator). Should be straightforward change, but I don't think I'll have time to do it, sorry!

**Comment by dschwoerer** [comment] 2021-02-22 10:23
Given that all tests got slower, and that is only on GHA - would it make sense to just accept that GHA is getting slower as more people are using it, and they don't provide enough resources to maintain the initial speed, and increase the timeouts to 10min - at least for debug builds?

Otherwise we could try to:
- [ ] make debug runs faster
- [ ] make tests faster in general - i.e. test less, or be otherwise smarter about what we do
- [ ] move to a faster CI - although GHA isn't that horrible slow, on other systems I needed to increase the timeout of test-coordinates-initialization from the default 3 seconds, as well as increase the general timeout above 10 minutes (currently set to 15)

**Comment by ZedThree** [comment] 2021-02-22 10:39
Bumping the timeout on just the debug builds is definitely the easiest, fastest thing to do, but also trying to make them run faster would be a good long term solution. I don't think we ever really profile anything in full debug mode, so that would be interesting to do, so I will try and do that this week.

Rewriting tests as unit tests is also a good way to make them faster. There's still a few that could probably be unit tests.

**Comment by ZedThree** [comment] 2021-02-22 15:24
One particular thing we could do for `test-drift-instability` and its staggered form is to drop the `Zeff = 2` case. Currently, we run three `Zeff` cases, 2, 32, and 256. The first case takes 2m17s on a debug build on my machine, while the other two take about 20s each.

I'm pretty sure most of `test-solver`  is spent in the karniadakis solver, that might be a good target for some optimisation work.

**Comment by johnomotani** [comment] 2021-02-22 15:37
> I'm pretty sure most of test-solver is spent in the karniadakis solver, that might be a good target for some optimisation work.

... or dropping the karniadakis solver. @bendudson may be able to confirm, but as far as I know it was an experiment that didn't take off and nobody uses.

**Comment by ZedThree** [comment] 2021-02-23 09:49
That's fairly accurate as far as my understanding goes. The registration system we've got means people could always revive it outside of the library and keep it as a runtime choice. I'm happy to remove karniadakis if there's no objections.

We can also remove `test-fieldfactory` (and `test-fieldfactory2` which doesn't even have a `runtest`), this has been completely replaced by unit tests.

I think `test-drift-instability` could also go in favour of the staggered version. We have plenty of non-staggered tests, we only run the non-staggered one on release, and I don't think it gives us any more info.

**Comment by bendudson** [comment] 2021-02-23 11:32
Hi @johnomotani @ZedThree Yes, Karniadakis was an experiment; the implementation as it is isn't very useful so should be removed. If the diffusion part were treated with backward Euler rather than forward Euler then it would be more useful, but then the IMEX-BDF2 scheme is probably better in that case. Happy for it to be removed.

**Comment by ZedThree** [comment] 2021-02-24 10:35
- Karniadakis removed in #2241 
- `test-drift-instability` made faster by dropping the most expensive case in #2240 

That might be sufficient to keep the timeout at 5 minutes

**Comment by ZedThree** [comment] 2021-06-23 09:05
Fixed in #2344

**Closed by ZedThree** 2021-06-23 09:05 UTC
