### ISSUE TITLE
Exceptions in BoutInitialise

### ISSUE THREAD

**Issue by johnomotani** [boutproject/BOUT-dev#1068] opened 2018-05-23 11:25 UTC
In BoutInitialise() we create the mesh and output file in a try clause which catches exceptions:
https://github.com/boutproject/BOUT-dev/blob/8389878169b4e4824c2d486dad7d9d65fa0db8c5/src/bout%2B%2B.cxx#L429-L433
My question is: why is the `BoutComm::cleanup();` in there? I managed to cause an error which threw an exception on only a couple of processes; the ones that threw hung in the `BoutComm::cleanup()` while the others were waiting in communication calls. Commenting out `BoutComm::cleanup();` resulted in the simulation terminating due to the exception, which is what I'd expect to happen.

**Comment by bendudson** [comment] 2018-05-23 11:30
I think this is just to try and tidy up; it frees the MPI communicator and calls MPI_Finalize:
https://github.com/boutproject/BOUT-dev/blob/next/src/sys/boutcomm.cxx#L11
Since cleanup with MPI, and error handling in general, is a bit of a mess, this could probably be removed.

**Comment by ZedThree** [comment] 2018-05-23 15:07
I wonder if it might be possible to do something like `BoutParallelThrowRhsFail`? Instead of rethrowing the exception, set a status, then do an allreduce outside of the catch block and call `BoutComm::cleanup()` if needed then?

**Comment by johnomotani** [comment] 2018-05-23 16:00
I don't see a way to do something like `BoutParallelThrowRhsFail` easily... That method relies on all processes calling `BoutParallelThrowRhsFail` at the same time. The problem I had/have was that an exception was thrown on only a couple of processors, leaving the others hanging on communications during initialisation, so they'd never get to error handling code at the end.

**Comment by bendudson** [comment] 2018-05-23 16:16
I think it depends on how terminal the failure is. I think it should work for cases where the exception was raised by BOUT++, but probably not for cases where MPI itself fails, or one of the nodes segfaults. I think it's an improvement anyway.

**Comment by ZedThree** [comment] 2018-05-31 10:58
@johnomotani If your error case is still reproducible, would you mind testing my code above as an alternative to #1069? If it doesn't make much of a difference, I'm happy for #1069 to go in as-is

**Comment by johnomotani** [comment] 2018-05-31 12:03
@ZedThree I can't remember now quite how I got the original error, but I can reproduce something similar artificially, and your code above does not handle it: if for example I throw an exception on just one processor in Coordinates::geometry(), then the adjacent processors get stuck at the call to communicate in geometry() and never get to the MPI_Allreduce(), while the rest of the processors get to the MPI_Allreduce() and then wait there.

**Comment by d7919** [comment] 2018-05-31 12:21
One option would be to call `cleanup` passing in an error code (e.g. 0 for normal cleanup and 1 for error state). In the error case we can do whatever cleanup is desired and then can use `mpi_abort` to force termination (e.g. using a simple timer and aborting if all processes don't reach cleanup within a specified time).

**Comment by ZedThree** [comment] 2018-06-05 16:32
I've merged #1069, but ideally we would find a better solution

**Closed by ZedThree** 2018-06-05 16:32 UTC
