### ISSUE TITLE
Error in make system related to linking with HDF5 

### ISSUE THREAD

**Issue by ADimits** [boutproject/BOUT-dev#961] opened 2018-03-22 21:06 UTC
The following issue was found when trying to build BOUT++ on/for the NERSC systems (e.g., CORI Haswell, with custom build NETCDF and HDF5.

When trying to build BOUT++ codes with a BOUT++ build that uses HDF5, either with 

--with-hdf5=PATH (location of h5cc) 

or with 

--with-netcdf

where the netcdf build is one that has the netcdf4 (hdf5-based) format enabled, the make.config file produced has the items

-lhdf5 -lhdf5_hl

in that order, which is the wrong order, and produces unsatisfied externals/symbols that prevent the build of codes dependent on the associated BOUT++ library build.

This order does not seem to correspond to that given by the h5cc script pointed to by the
--with-hdf5=PATH option.

Having these in the opposite order, i.e.,

-lhdf5_hl -lhdf5

seems to work robustly. 

The simple kludge/temporary fix is just to hand edit the make.config file, but I do not understand the autoconf/make system well enough to know how to make a "permanent" fix.

**Comment by d7919** [comment] 2018-03-23 08:40
Thanks for reporting this. @ZedThree is working on the configure script at the moment so I'll assign this to him.

Which version (/commit hash/branch) of BOUT++ are you using?

**Comment by ZedThree** [comment] 2018-03-23 10:32
This turns out to be a bug in the upstream [`ax_lib_hdf5.m4` macro][1] from the autoconf archive. The issue is that they iterate over all the flags from the `h5cc -showconfig` and then reassemble them into the appropriate variable (`HDF5_LIBS` in the case of `-l` flags), but *in reverse order*. This is likely only an issue if you have built only static versions of the HDF5 libraries.

I've got a fix, I'll get it into master and next, and then submit it upstream.


[1]: https://www.gnu.org/software/autoconf-archive/ax_lib_hdf5.html

**Closed** 2018-03-23 12:54 UTC
Labels: bug
