### ISSUE TITLE
commandline options not recognized should halt program execution

### ISSUE THREAD

**Issue by JensMadsen** [boutproject/BOUT-dev#233] opened 2016-09-09 12:03 UTC
For instance

giving nype at the commandline is not recognized, but no error.

**Comment by bendudson** [comment] 2016-09-09 12:41
This is a little difficult, because:
1. There is no way to know which options will be used until the program has
run. Options are put into a database (tree), then requested by various
parts of the code as it runs. Perhaps unused options could be checked after
the first iteration, when hopefully all options have been used?

2.Some options on the command line may be used by other libraries e.g.
PETSc. Also difficult to tell which are unused, so PETSc prints unused
options at the end of the run.

**Comment by JensMadsen** [comment] 2016-09-12 07:48
Ok. If it is difficult then perhaps a warning after BoutInitialise if options have not been used?

**Comment by dschwoerer** [comment] 2016-12-06 16:05
Duplicate of #35 

Can be closed

**Closed** 2016-12-09 14:33 UTC
Labels: enhance request
