### ISSUE TITLE
Add capability to write strings to datafile

### ISSUE THREAD

**Issue by JensMadsen** [boutproject/BOUT-dev#520] opened 2017-04-18 13:22 UTC
The motivation for this enhance request is to be able to write less error prone code. 

As an example I have a code which incorporates multiple models for collisional effects. In that case it would be handy to be able to store the model name instead if (what I do now) to store the int associated with an enum

**Comment by dschwoerer** [comment] 2017-04-18 13:49
duplicate of #222

**Closed** 2017-04-18 13:55 UTC
Labels: duplicate, enhance request
