### ISSUE TITLE
Fedora rawhide test failing due to out of date shell

### ISSUE THREAD

**Issue by ZedThree** [boutproject/BOUT-dev#2143] opened 2020-11-18 11:14 UTC
The Fedora test is failing with the following error:

```
./configure: This script requires a shell more modern than all
./configure: the shells that I found on your system.
./configure: Please tell bug-autoconf@gnu.org and bd512@york.ac.uk
./configure: about your system, including any error possibly output
./configure: before this message. Then install a modern shell, or
./configure: manually run the script under such a shell if you do
./configure: have one.
```

I guess Fedora rawhide recently changed /bin/sh, but I can't find what that change was. @dschwoerer any ideas what's caused this?

Not sure what we need to do to fix this -- possibly run `autoreconf -fvi` as part of the fedora test? Or maybe just shift it over to use CMake instead?

**Comment by dschwoerer** [comment] 2020-11-18 12:24
I tried to restart, but for some reason it isn't running:
https://travis-ci.org/github/boutproject/BOUT-dev/jobs/742975318

I tried to run `./configure` in fedora rawhide container, but that did work without issues.
I had weird issues with docker on travis in the past, and in that case I solved it by switching the ubuntu version.

**Comment by ZedThree** [comment] 2020-11-18 13:35
Is that container freshly built? What's `sh --version`?

**Comment by ZedThree** [comment] 2020-11-19 10:38
It seems it works in a container but not in an image! At the minute my top suspect is `test -x /` is for some reason returning false -- currently trying to pinpoint _why_

**Comment by ZedThree** [comment] 2020-11-19 10:57
`test -x /` fails in rawhide but not latest. Reproducer:

```
#!/bin/sh
set -ex
if [ ".$1" = .podman ]
then
    if test $1 = podman ; then
	    cmd=podman
    else
	    cmd="sudo docker"
    fi
    test . != ".$2" && version="$2" || version=rawhide
    time $cmd pull registry.fedoraproject.org/fedora:$version
    time $cmd create --name podman_mvce registry.fedoraproject.org/fedora:$version \
	     /tmp/podman_repro.sh
    time $cmd cp $(pwd)/podman_repro.sh podman_mvce:/tmp
    time $cmd start -a podman_mvce
    exit 0
fi

if [ $UID -eq 0 ]
then
    useradd test
    sudo -u test $0
else
    sh --version
    cat /etc/*release
    ls -la /
    if test -x /; then
        echo "root executable"
    else
        echo "root not executable"
    fi
fi
```

Adding `--cap-add=SYS_PTRACE --security-opt seccomp=unconfined` to the `$cmd create` line seems to fix this. But I still don't know what rawhide has changed to make this necessary now (or why `configure` needs to check `/` is executable?!)

**Comment by dschwoerer** [comment] 2020-11-19 16:34
I cannot reproduce this either:
```
podman rm podman_mvce ; sh podman_repro.sh podman
15a79b997e9673c5bb320e74f1c8645f9f7598e52cf905f88c250dd8b1f9c7c2
+ '[' .podman = .podman ']'
+ test podman = podman
+ cmd=podman
+ test . '!=' .
+ version=rawhide
+ podman pull registry.fedoraproject.org/fedora:rawhide
Trying to pull registry.fedoraproject.org/fedora:rawhide...
Getting image source signatures
Copying blob 2738316dcd34 [--------------------------------------] 0.0b / 0.0b
Copying config 3403832bc4 done  
Writing manifest to image destination
Storing signatures
3403832bc452fc05dff4c87651f266e3d01cc16cece9e26c96a4489f89079f03

real	0m1.717s
user	0m0.163s
sys	0m0.119s
+ podman create --name podman_mvce registry.fedoraproject.org/fedora:rawhide /tmp/podman_repro.sh
389328410f34a731fe48ba463602c49a914007e1e888f9e22403015e9445deb4

real	0m0.314s
user	0m0.108s
sys	0m0.103s
++ pwd
+ podman cp /home/dave/soft/bout-dev/podman_repro.sh podman_mvce:/tmp

real	0m0.828s
user	0m0.307s
sys	0m0.425s
+ podman start -a podman_mvce
+ '[' . = .podman ']'
+ '[' 0 -eq 0 ']'
+ useradd test
+ sudo -u test /tmp/podman_repro.sh
+ '[' . = .podman ']'
+ '[' 1000 -eq 0 ']'
+ sh --version
GNU bash, version 5.0.17(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
+ cat /etc/fedora-release /etc/os-release /etc/redhat-release /etc/system-release
Fedora release 34 (Rawhide)
NAME=Fedora
VERSION="34 (Container Image Prerelease)"
ID=fedora
VERSION_ID=34
VERSION_CODENAME=""
PLATFORM_ID="platform:f34"
PRETTY_NAME="Fedora 34 (Container Image Prerelease)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:34"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/rawhide/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=rawhide
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=rawhide
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Container Image"
VARIANT_ID=container
Fedora release 34 (Rawhide)
Fedora release 34 (Rawhide)
+ ls -la /
total 16
drwxr-xr-x.  18 root   root     6 Nov 19 14:24 .
lrwxrwxrwx.   1 root   root     7 Oct 29 07:33 bin -> usr/bin
dr-xr-xr-x.   2 root   root     0 Oct 29 07:33 boot
drwxr-xr-x.   5 root   root   340 Nov 19 14:24 dev
drwxr-xr-x.  43 root   root   438 Nov 19 14:24 etc
drwxr-xr-x.   3 root   root     8 Nov 19 14:24 home
lrwxrwxrwx.   1 root   root     7 Oct 29 07:33 lib -> usr/lib
lrwxrwxrwx.   1 root   root     9 Oct 29 07:33 lib64 -> usr/lib64
drwx------.   2 root   root     0 Nov 19 09:17 lost+found
drwxr-xr-x.   2 root   root     0 Oct 29 07:33 media
drwxr-xr-x.   2 root   root     0 Oct 29 07:33 mnt
drwxr-xr-x.   2 root   root     0 Oct 29 07:33 opt
dr-xr-xr-x. 350 nobody nobody   0 Nov 19 14:24 proc
dr-xr-x---.   2 root   root   236 Nov 19 09:18 root
drwxr-xr-x.   3 root   root    40 Nov 19 14:24 run
lrwxrwxrwx.   1 root   root     8 Oct 29 07:33 sbin -> usr/sbin
drwxr-xr-x.   2 root   root     0 Oct 29 07:33 srv
dr-xr-xr-x.  13 nobody nobody   0 Nov 16 08:37 sys
drwxrwxrwt.   2 root   root    70 Nov 19 14:24 tmp
drwxr-xr-x.  12 root   root   100 Nov 19 09:17 usr
drwxr-xr-x.  18 root   root    10 Nov 19 14:24 var
+ test -x /
root executable
+ echo 'root executable'

real	0m1.372s
user	0m0.117s
sys	0m0.181s
+ exit 0
```

That might have been fixed, but there might be other thinks that are confusing `configure`.
I am not opposed to merging #2146, especially if you need to test something, but I would prefer to properly resolve this. Relaxed restrictions shouldn't be required for BOUT++.

I tried running `./configure` but without installing anything, and configure runs but complains about `mpic++`. If Travis shows the same result, I can dig into what package causes the breakage. Unfortunately travis is currently extremly slow. Also my own PC isn't that great either ...

Concerning `test -x /` - if that flag isn't set, then the user cannot do [basically anything](https://unix.stackexchange.com/a/317446). Did only `test` return the wrong result, or was the output of `ls` also restricted?

**Comment by ZedThree** [comment] 2020-11-19 16:59
What's your host system? Maybe try it in a Ubuntu container? The repro script only takes a couple of seconds for me.
Also this only fails for me in rawhide and not latest.

Nope, `ls` works fine:

```
+ cat /etc/fedora-release /etc/os-release /etc/redhat-release /etc/system-release
Fedora release 34 (Rawhide)
NAME=Fedora
VERSION="34 (Container Image Prerelease)"
ID=fedora
VERSION_ID=34
VERSION_CODENAME=""
PLATFORM_ID="platform:f34"
PRETTY_NAME="Fedora 34 (Container Image Prerelease)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:34"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/rawhide/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=rawhide
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=rawhide
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Container Image"
VARIANT_ID=container
Fedora release 34 (Rawhide)
Fedora release 34 (Rawhide)
+ ls -la /
total 4
drwxr-xr-x  18 root   root     17 Nov 19 16:38 .
lrwxrwxrwx   1 root   root      7 Oct 29 07:33 bin -> usr/bin
dr-xr-xr-x   2 root   root      6 Oct 29 07:33 boot
drwxr-xr-x   5 root   root    340 Nov 19 16:38 dev
drwxr-xr-x  43 root   root   4096 Nov 19 16:38 etc
drwxr-xr-x   3 root   root     18 Nov 19 16:38 home
lrwxrwxrwx   1 root   root      7 Oct 29 07:33 lib -> usr/lib
lrwxrwxrwx   1 root   root      9 Oct 29 07:33 lib64 -> usr/lib64
drwx------   2 root   root      6 Nov 19 09:17 lost+found
drwxr-xr-x   2 root   root      6 Oct 29 07:33 media
drwxr-xr-x   2 root   root      6 Oct 29 07:33 mnt
drwxr-xr-x   2 root   root      6 Oct 29 07:33 opt
dr-xr-xr-x 484 nobody nobody    0 Nov 19 16:38 proc
dr-xr-x---   2 root   root    196 Nov 19 09:18 root
drwxr-xr-x   2 root   root     27 Nov 19 16:38 run
lrwxrwxrwx   1 root   root      8 Oct 29 07:33 sbin -> usr/sbin
drwxr-xr-x   2 root   root      6 Oct 29 07:33 srv
dr-xr-xr-x  13 nobody nobody    0 Nov 19 16:38 sys
drwxrwxrwt   2 root   root     57 Nov 19 16:38 tmp
drwxr-xr-x  12 root   root    144 Nov 19 09:17 usr
drwxr-xr-x  18 root   root     19 Nov 19 16:38 var
+ test -x /
+ echo 'root not executable'
root not executable
```

`test -x` actually fails for all directories I tested, but `ls`, `cd` etc all work. So something broken in `test` maybe?

**Comment by ZedThree** [comment] 2020-11-20 09:23
@dschwoerer I agree it would be better to get to the bottom of this, but the failing test is holding up several PRs. Let's merge #2146 for now, we can always fix it properly later (assuming we get a better fix)

We should probably report this somewhere as a bug, I'm just not sure if it's in podman or rawhide.

**Comment by ZedThree** [comment] 2020-11-20 10:10
Bit more of a clue: `test` is the bash builtin here, and `/usr/bin/test -x /` does work correctly. I also checked `zsh`:

```
+ test -x /
root not executable with bash builtin
+ echo 'root not executable with bash builtin'
+ zsh -c 'test -x /'
root executable with zsh builtin
+ echo 'root executable with zsh builtin'
+ /usr/bin/test -x /
root executable with coreutils /usr/bin/test
test is a shell builtin
+ echo 'root executable with coreutils /usr/bin/test'
+ type test
```

I've been looking here for changes to rawhide, but can't see any changes to bash in the relevant time period: https://lists.fedoraproject.org/archives/search?q=bash&page=1&mlist=devel%40lists.fedoraproject.org&sort=date-desc

**Comment by dschwoerer** [comment] 2020-11-20 11:20
Noticed this as well. Also it is not podman specific.
```
+ sudo docker run --rm -it registry.fedoraproject.org/fedora:rawhide /usr/bin/test -x /
+ echo 0
0
+ sudo docker run --rm -it registry.fedoraproject.org/fedora:rawhide /usr/bin/bash -c test -x /
+ echo 1
1
+ podman run --rm -it registry.fedoraproject.org/fedora:rawhide /usr/bin/test -x /
+ echo 0
0
+ podman run --rm -it registry.fedoraproject.org/fedora:rawhide /usr/bin/bash -c test -x /
+ echo 1
1
```

There was also no build of bash recently: https://koji.fedoraproject.org/koji/packageinfo?packageID=1088

Reported here: https://bugzilla.redhat.com/show_bug.cgi?id=1899913

**Comment by dschwoerer** [comment] 2020-11-20 15:16
This is fixed by: https://github.com/systemd/systemd/pull/16739

All we need is ubuntu shipping the fix.

**Closed by dschwoerer** 2020-11-20 15:16 UTC
